import { z } from 'zod';
import { Platform, schemaVersion, timestamps, workspaceScoped } from './common';

export const ShortVideoConceptType = z.enum([
  'one_powerful_insight',
  'common_mistake',
  'mini_tutorial',
  'myth_correction',
  'strong_opinion',
  'before_and_after',
  'framework_breakdown',
  'story_moment',
  'checklist',
  'question_and_answer',
]);

const shortScriptBeatSchema = z.object({
  startSeconds: z.number().nonnegative(),
  endSeconds: z.number().positive(),
  voice: z.string().min(1),
  visual: z.string().min(1),
  onScreenText: z.string().optional(),
});

/**
 * Generated by Module 5 (Repurposing Engine) from an approved MasterVideo,
 * never independently from the raw transcript.
 */
export const ShortVideoSchemaV1 = z.object({
  schemaVersion: schemaVersion(1),
  ...workspaceScoped,
  masterVideoId: z.string().uuid(),
  masterVideoVersionId: z.string().uuid(),

  conceptType: ShortVideoConceptType,
  title: z.string().min(1),
  hook: z.string().min(1),
  script: z.array(shortScriptBeatSchema).min(1),
  durationSeconds: z.number().int().positive(),
  platforms: z.array(Platform).min(1),
  caption: z.string().min(1),
  cta: z.string().min(1),
  connectionToLongForm: z.string().min(1),

  ...timestamps,
});
export type ShortVideo = z.infer<typeof ShortVideoSchemaV1>;

export const ShortVideoSchema = ShortVideoSchemaV1;
